### ISSUE TITLE
No Activity found to handle Intent for createDocument and openDocument

### ISSUE THREAD

**Issue by HassanHeydariNasab** [ammarahm-ed/react-native-scoped-storage#2]
```
FATAL EXCEPTION: mqt_native_modules

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT }

FATAL EXCEPTION: mqt_native_modules
Process: com.ahangap.app, PID: 10760
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
	at android.app.Activity.startActivityForResult(Activity.java:5320)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:5278)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at com.ammarahmed.scopedstorage.RNScopedStorageModule.createDocument(RNScopedStorageModule.java:297)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:923)
```

```
FATAL EXCEPTION: mqt_native_modules

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT }

FATAL EXCEPTION: mqt_native_modules
Process: com.ahangap.app, PID: 11102
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
	at android.app.Activity.startActivityForResult(Activity.java:5320)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:5278)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at com.ammarahmed.scopedstorage.RNScopedStorageModule.openDocument(RNScopedStorageModule.java:355)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by ammarahm-ed** [comment]
What device are you testing this on?

**Comment by HassanHeydariNasab** [comment]
> What device are you testing this on?

Nokia 2.2
Android 11

**Comment by GaneshH-Sankey** [comment]
> What device are you testing this on?

Hey, on which react native version this library supposed to work, because NativeModules imported in index.tsx file dont have RNFSManager, getting undefined error because of that, im using react native 0.59.9

**Comment by GaneshH-Sankey** [comment]
> What device are you testing this on?

Same issue occurin for writeFile function

**Comment by ammarahm-ed** [comment]
Issue is fixed on master. Will come in next release
