### ISSUE TITLE
Not able to run this respository after cloning the same following is the error

### ISSUE THREAD

**Issue by fsd2** [ammarahm-ed/react-native-scoped-storage#3]
Last login: Thu Aug 26 19:30:45 on ttys001
fsd2@Nikhils-MacBook-Pro ~ % /Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/react-native/scripts/launchPackager.command ; exit;

                                                      
                        #######                       
                   ################                   
                #########     #########               
            #########             ##########          
        #########        ######        #########      
       ##########################################     
      #####      #####################       #####    
      #####          ##############          #####    
      #####    ###       ######       ###    #####    
      #####    #######            #######    #####    
      #####    ###########    ###########    #####    
      #####    ##########################    #####    
      #####    ##########################    #####    
      #####      ######################     ######    
       ######        #############        #######     
         #########        ####       #########        
              #########          #########            
                  ######### #########                 
                       #########                      
                                                      
                                                      
                    Welcome to Metro!
              Fast - Scalable - Integrated

To reload the app press "r"
To open developer menu press "d"

 BUNDLE  ./index.js 

error: Error: While trying to resolve module `react-native-scoped-storage` from file `/Users/fsd/Downloads/react-native-scoped-storage-master/example/App.tsx`, the package `/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/react-native-scoped-storage/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/react-native-scoped-storage/index.js`. Indeed, none of these files exist:

  * /Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/react-native-scoped-storage/index.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * /Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/react-native-scoped-storage/index.js/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency (/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/node-haste/DependencyGraph.js:436:17)
    at Object.resolve (/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
    at _next (/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:9)
info Reloading app...
 BUNDLE  ./index.tsx 

error: Error: While trying to resolve module `react-native-scoped-storage` from file `/Users/fsd/Downloads/react-native-scoped-storage-master/example/App.tsx`, the package `/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/react-native-scoped-storage/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/react-native-scoped-storage/index.js`. Indeed, none of these files exist:

  * /Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/react-native-scoped-storage/index.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * /Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/react-native-scoped-storage/index.js/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency (/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/node-haste/DependencyGraph.js:436:17)
    at Object.resolve (/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
    at _next (/Users/fsd/Downloads/react-native-scoped-storage-master/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:9)

**Comment by ammarahm-ed** [comment]
It points to a index.tsx file which does exist. not sure why you are getting this error. can you try again?
